USE LOLABUM;

-- Renombrar la tabla PEDIDO a INTENCION_COMPRA
EXEC sp_rename 'dbo.PEDIDO', 'INTENCION_COMPRA';


-- Añadir una nueva columna temporal
ALTER TABLE VEHICULOS
ADD TempPrecio INT;

-- Actualizar la nueva columna con los valores convertidos
UPDATE VEHICULOS
SET TempPrecio = CONVERT(INT, PRECIO);

-- Eliminar la columna original
ALTER TABLE VEHICULOS
DROP COLUMN PRECIO;

-- Renombrar la nueva columna a la nomenclatura original
EXEC sp_rename 'VEHICULOS.TempPrecio', 'PRECIO', 'COLUMN';



ALTER TABLE CATEGORIA
ADD ESTADO BIT;

ALTER TABLE PERSONA
ADD ESTADO BIT;

ALTER TABLE CLIENTE
ADD ESTADO BIT;

ALTER TABLE EMPLEADO
ADD ESTADO BIT;

ALTER TABLE INTENCION_COMPRA
ADD ESTADO BIT;

ALTER TABLE INTENCION_COMPRA
ADD ESTADO_INTENCION_COMPRA BIT;

ALTER TABLE FACTURA
ADD ESTADO BIT;

ALTER TABLE VEHICULOS
ADD ESTADO BIT;

ALTER TABLE CONCESCIONARIO
ADD ESTADO BIT;

