USE LOLABUM;

-- Renombrar la tabla PEDIDO a INTENCION_COMPRA
EXEC sp_rename 'dbo.PEDIDO', 'INTENCION_COMPRA';



ALTER TABLE CATEGORIA
ADD ESTADO BIT;

ALTER TABLE PERSONA
ADD ESTADO BIT;

ALTER TABLE CLIENTE
ADD ESTADO BIT;

ALTER TABLE EMPLEADO
ADD ESTADO BIT;

ALTER TABLE INTENCION_COMPRA
ADD ESTADO BIT;

ALTER TABLE INTENCION_COMPRA
ADD ESTADO_INTENCION_COMPRA BIT;

ALTER TABLE FACTURA
ADD ESTADO BIT;

ALTER TABLE VEHICULOS
ADD ESTADO BIT;

ALTER TABLE CONCESCIONARIO
ADD ESTADO BIT;

