-- Valores de ejemplo para la tabla PERSONAS-------

INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (123456789, 'Juan', 'Carlos', 'Pérez', 'González', 28, 'juan@example.com', 1234567890,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (124454789, 'María', 'Isabel', 'Gómez', 'López', 35, 'maria@example.com', 1234567891,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (124454791, 'Luis', 'Fernando', 'Martínez', 'Rodríguez', 42, 'luis@example.com', 1234567892,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (124454792, 'Ana', 'María', 'Ramírez', 'Sánchez', 29, 'ana@example.com', 1234567893,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (124454793, 'Carlos', 'Andrés', 'López', 'Vargas', 31, 'carlos@example.com', 1234567894,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (345678901, 'Laura', 'Elena', 'García', 'Hernández', 25, 'laura@example.com', 1234567895,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (567890123, 'Pedro', 'Antonio', 'Díaz', 'Pérez', 39, 'pedro@example.com', 1234567896,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (678901234, 'Carmen', 'Isabel', 'Torres', 'Rojas', 45, 'carmen@example.com', 1234567897,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (890123456, 'Miguel', 'Ángel', 'Rivas', 'Gutiérrez', 34, 'miguel@example.com', 1234567898,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (901234567, 'Paula', 'Alejandra', 'Navarro', 'Castillo', 28, 'paula@example.com', 1234567899,'TRUE');

INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (111222333, 'Alejandro', 'David', 'García', 'López', 31, 'alejandro@example.com', 1112223330,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (444555666, 'María', 'José', 'Fernández', 'Pérez', 28, 'maria@example.com', 1234567871,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (777888999, 'Andrés', 'Javier', 'Hernández', 'Rodríguez', 37, 'andres@example.com', 1234567872,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (222333444, 'Luisa', 'Fabiola', 'Jiménez', 'Gutiérrez', 25, 'luisa@example.com', 1234567873,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (555666777, 'Daniel', 'Eduardo', 'Torres', 'Sánchez', 29, 'daniel@example.com', 1234567874,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (888999000, 'Carolina', 'Isabella', 'Cruz', 'Martínez', 32, 'carolina@example.com', 1234567875,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (333444555, 'Fernando', 'Miguel', 'Díaz', 'Ramírez', 27, 'fernando@example.com', 1234567876,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (666777888, 'Laura', 'Valentina', 'Ortega', 'Vargas', 34, 'laura@example.com', 1234567877,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (999000111, 'Gabriel', 'Sebastián', 'Ruiz', 'Castro', 26, 'gabriel@example.com', 1234567878,'TRUE');
INSERT INTO PERSONA (IDENTIFICACION,NOMBRE_1,NOMBRE_2,APELLIDO_1,APELLIDO_2,EDAD,CORREO,TELEFONO,ESTADO)VALUES (123456700, 'Victoria', 'Catalina', 'Moreno', 'Luna', 30, 'victoria@example.com', 1234567879,'TRUE');


-- Valores de ejemplo para la tabla CLIENTE (relacionados con PERSONAS existentes)--------
INSERT INTO CLIENTE (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1008, 'Juan', '121234','TRUE');
INSERT INTO CLIENTE (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1009, 'María', 'GSG387','TRUE');
INSERT INTO CLIENTE (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1010, 'Luis', 'KHR467','TRUE');
INSERT INTO CLIENTE (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1011, 'Ana', '234MVB','TRUE');
INSERT INTO CLIENTE (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1012, 'Carlos', '342780','TRUE');
INSERT INTO CLIENTE (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1013, 'Laura', 'KIN446','TRUE');
INSERT INTO CLIENTE (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1014, 'Pedro', '203KGI','TRUE');
INSERT INTO CLIENTE (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1015, 'Carmen', '234111','TRUE');
INSERT INTO CLIENTE (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1015, 'Miguel', '474700','TRUE');
INSERT INTO CLIENTE (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1016, 'Paula', 'PAN221','TRUE');

-- Valores de ejemplo para la tabla EMPLEADO (relacionados con PERSONAS existentes)
INSERT INTO EMPLEADO (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1017, 'Alejandro', 'HDI456','TRUE');
INSERT INTO EMPLEADO (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1018, 'María', 'POD456','TRUE');
INSERT INTO EMPLEADO (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1019, 'Andrés', '987067','TRUE');
INSERT INTO EMPLEADO (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1020, 'Luisa', 'TQM345','TRUE');
INSERT INTO EMPLEADO (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1021, 'Daniel', 'GTO456','TRUE');
INSERT INTO EMPLEADO (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1022, 'Carolina', 'UJB567','TRUE');
INSERT INTO EMPLEADO (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1023, 'Fernando', '345TGB','TRUE');
INSERT INTO EMPLEADO (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1024, 'Laura', 'WDV234','TRUE');
INSERT INTO EMPLEADO (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1025, 'Gabriel', 'QSX345','TRUE');
INSERT INTO EMPLEADO (ID_PERSONA,USUARIO,CONTRASENA,ESTADO)VALUES (1026, 'Victoria', 'UKM236','TRUE');


-- Valores de ejemplo para la tabla INTENCION_COMPRA (relacionados con CLIENTES y VEHÍCULOS existentes)
INSERT INTO INTENCION_COMPRA (DESCRIPCION_INTENCION_COMPRA,ID_CLIENTE,ID_VEHICULOS,ID_FACTURA,ESTADO,ESTADO_INTENCION_COMPRA)VALUES('Motocicleta blanca', 1002,1012,1002,'TRUE','TRUE');
INSERT INTO INTENCION_COMPRA (DESCRIPCION_INTENCION_COMPRA,ID_CLIENTE,ID_VEHICULOS,ID_FACTURA,ESTADO,ESTADO_INTENCION_COMPRA)VALUES('Bicicleta eléctrica plegable',1003, 1013,1003,'TRUE','FALSE');
INSERT INTO INTENCION_COMPRA (DESCRIPCION_INTENCION_COMPRA,ID_CLIENTE,ID_VEHICULOS,ID_FACTURA,ESTADO,ESTADO_INTENCION_COMPRA)VALUES('Scooter eléctrico rojo', 1004,1014,1004,'TRUE','TRUE');
INSERT INTO INTENCION_COMPRA (DESCRIPCION_INTENCION_COMPRA,ID_CLIENTE,ID_VEHICULOS,ID_FACTURA,ESTADO,ESTADO_INTENCION_COMPRA)VALUES('Motocicleta deportiva', 1005,1015,1005,'TRUE','TRUE');
INSERT INTO INTENCION_COMPRA (DESCRIPCION_INTENCION_COMPRA,ID_CLIENTE,ID_VEHICULOS,ID_FACTURA,ESTADO,ESTADO_INTENCION_COMPRA)VALUES('Bicicleta eléctrica de montaña',1006, 1016,1006,'TRUE','FALSE');
INSERT INTO INTENCION_COMPRA (DESCRIPCION_INTENCION_COMPRA,ID_CLIENTE,ID_VEHICULOS,ID_FACTURA,ESTADO,ESTADO_INTENCION_COMPRA)VALUES('Scooter eléctrico negro', 1007,1017,1007,'TRUE','FALSE');
INSERT INTO INTENCION_COMPRA (DESCRIPCION_INTENCION_COMPRA,ID_CLIENTE,ID_VEHICULOS,ID_FACTURA,ESTADO,ESTADO_INTENCION_COMPRA)VALUES('Motocicleta urbana', 1008,1018,1008,'TRUE','TRUE');
INSERT INTO INTENCION_COMPRA (DESCRIPCION_INTENCION_COMPRA,ID_CLIENTE,ID_VEHICULOS,ID_FACTURA,ESTADO,ESTADO_INTENCION_COMPRA)VALUES('Bicicleta eléctrica cruiser', 1009,1019,1009,'TRUE','TRUE');
INSERT INTO INTENCION_COMPRA (DESCRIPCION_INTENCION_COMPRA,ID_CLIENTE,ID_VEHICULOS,ID_FACTURA,ESTADO,ESTADO_INTENCION_COMPRA)VALUES('Scooter eléctrico blanco', 1010,1020,1010,'TRUE','FALSE');
INSERT INTO INTENCION_COMPRA (DESCRIPCION_INTENCION_COMPRA,ID_CLIENTE,ID_VEHICULOS,ID_FACTURA,ESTADO,ESTADO_INTENCION_COMPRA)VALUES('Motocicleta elegante', 1011,1021,1011,'TRUE','FALSE');


-- Valores de ejemplo para la tabla FACTURA (relacionados con INTENCION_COMPRAS existentes)FALSE FALSE
INSERT INTO FACTURA (FECHA_FACTURA,ESTADO_FACTURA,ESTADO)VALUES('2023-08-23', 'FALSE','TRUE');
INSERT INTO FACTURA (FECHA_FACTURA,ESTADO_FACTURA,ESTADO)VALUES('2023-08-24', 'TRUE','TRUE');
INSERT INTO FACTURA (FECHA_FACTURA,ESTADO_FACTURA,ESTADO)VALUES('2023-08-25', 'FALSE','TRUE');
INSERT INTO FACTURA (FECHA_FACTURA,ESTADO_FACTURA,ESTADO)VALUES('2023-08-25', 'FALSE','TRUE');
INSERT INTO FACTURA (FECHA_FACTURA,ESTADO_FACTURA,ESTADO)VALUES('2023-08-26', 'TRUE','TRUE');
INSERT INTO FACTURA (FECHA_FACTURA,ESTADO_FACTURA,ESTADO)VALUES('2023-08-26', 'FALSE','TRUE');
INSERT INTO FACTURA (FECHA_FACTURA,ESTADO_FACTURA,ESTADO)VALUES('2023-08-27', 'TRUE','TRUE');
INSERT INTO FACTURA (FECHA_FACTURA,ESTADO_FACTURA,ESTADO)VALUES('2023-08-28', 'FALSE','TRUE');
INSERT INTO FACTURA (FECHA_FACTURA,ESTADO_FACTURA,ESTADO)VALUES('2023-08-29', 'FALSE','TRUE');
INSERT INTO FACTURA (FECHA_FACTURA,ESTADO_FACTURA,ESTADO)VALUES('2023-08-29', 'TRUE','TRUE');


-- Valores de ejemplo para la tabla CATEGORIA
INSERT INTO CATEGORIA (NOMBRE,ESTADO)VALUES ('Motocicleta eléctricas','TRUE');
INSERT INTO CATEGORIA (NOMBRE,ESTADO)VALUES ('Bicicletas eléctricas','TRUE');
INSERT INTO CATEGORIA (NOMBRE,ESTADO)VALUES ('Scooter eléctricos','TRUE');


-- Valores de ejemplo para la tabla CONCESCIONARIO
INSERT INTO CONCESCIONARIO (NOMBRE,DIRECCION,TELEFONO,CORREO,ESTADO)VALUES ('Be Electric','Carrera 18 #88 – 18',1234456,'BeElectric@energ.com.co','TRUE');
INSERT INTO CONCESCIONARIO (NOMBRE,DIRECCION,TELEFONO,CORREO,ESTADO)VALUES ('Niu Motocicletas Eléctricas','Carrera 15 #86B – 13',7654987,'niucolombia8924@niu.com.co','TRUE');
INSERT INTO CONCESCIONARIO (NOMBRE,DIRECCION,TELEFONO,CORREO,ESTADO)VALUES ('Auteco Mobility','Carrera 11 #22 – 15',3456789,'servicioalcliente@auteco.com.co','TRUE');
INSERT INTO CONCESCIONARIO (NOMBRE,DIRECCION,TELEFONO,CORREO,ESTADO)VALUES('Concesionario de Vehículos Eléctricos', 'Avenida 12 # 56 - 98 ', 123456789, 'ventas@concesionarioelectricos.com','TRUE');
INSERT INTO CONCESCIONARIO (NOMBRE,DIRECCION,TELEFONO,CORREO,ESTADO)VALUES('ElectroCars Showroom','Calle 45 # 45 c 44 este', 1123456789, 'info@electrocars.com','TRUE');
INSERT INTO CONCESCIONARIO (NOMBRE,DIRECCION,TELEFONO,CORREO,ESTADO)VALUES('EcoMobility Dealers', 'Calle 87 b # 34 g 12 ', 543216789, 'contacto@ecomobilitydealers.com','TRUE');
INSERT INTO CONCESCIONARIO (NOMBRE,DIRECCION,TELEFONO,CORREO,ESTADO)VALUES('GreenRide Auto', 'Calle 89 # 10 - 45 ', 678912345, 'ventas@greenrideauto.com','TRUE');
INSERT INTO CONCESCIONARIO (NOMBRE,DIRECCION,TELEFONO,CORREO,ESTADO)VALUES('EcoMotion Motocicletars', 'Avenida 43 # 26 - 13 este ', 789123456, 'info@ecomotionMotocicletars.com','TRUE');


-- Valores de ejemplo para la tabla VEHICULOS (relacionados con CATEGORÍAS y CONCESIONARIOS existentes)
INSERT INTO VEHICULOS (NOMBRE,PRECIO,ID_CATEGORIA,ID_CONCESIONARIO,ESTADO)VALUES('Motocicleta Eléctrica SportX', '15.900.000', 1002, 1002,'TRUE');
INSERT INTO VEHICULOS (NOMBRE,PRECIO,ID_CATEGORIA,ID_CONCESIONARIO,ESTADO)VALUES('Bicicleta Eléctrica UrbanCruiser', '3.190.000', 1002, 1003,'TRUE');
INSERT INTO VEHICULOS (NOMBRE,PRECIO,ID_CATEGORIA,ID_CONCESIONARIO,ESTADO)VALUES('Scooter Eléctrico SwiftRide', '1.399.900', 1003, 1004,'TRUE');
INSERT INTO VEHICULOS (NOMBRE,PRECIO,ID_CATEGORIA,ID_CONCESIONARIO,ESTADO)VALUES('Motocicleta Eléctrica EcoRider', '14.780.000', 1004, 1005,'TRUE');
INSERT INTO VEHICULOS (NOMBRE,PRECIO,ID_CATEGORIA,ID_CONCESIONARIO,ESTADO)VALUES('Bicicleta Eléctrica TrailBlazer', '4.150.000', 1004, 1006,'TRUE');
INSERT INTO VEHICULOS (NOMBRE,PRECIO,ID_CATEGORIA,ID_CONCESIONARIO,ESTADO)VALUES('Scooter Eléctrico CityGlide', '1.450.000', 1002, 1007,'TRUE');
INSERT INTO VEHICULOS (NOMBRE,PRECIO,ID_CATEGORIA,ID_CONCESIONARIO,ESTADO)VALUES('Motocicleta Eléctrica Speedster', '19.500.000', 1003, 1004,'TRUE');
INSERT INTO VEHICULOS (NOMBRE,PRECIO,ID_CATEGORIA,ID_CONCESIONARIO,ESTADO)VALUES('Bicicleta Eléctrica CommuterX', '6.130.500', 1002, 1008,'TRUE');
INSERT INTO VEHICULOS (NOMBRE,PRECIO,ID_CATEGORIA,ID_CONCESIONARIO,ESTADO)VALUES('Scooter Eléctrico PowerGlide', '1.550.000', 1004, 1009,'TRUE');
INSERT INTO VEHICULOS (NOMBRE,PRECIO,ID_CATEGORIA,ID_CONCESIONARIO,ESTADO)VALUES('Motocicleta Eléctrica ThunderBolt', '18.200.000', 1002, 1006,'TRUE');
